version: '3.1'

services:
  proxy:
    image: nginx_proxy
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - localhost.crt
      - localhost.key
    networks:
      - appnet

secrets:
  localhost.crt:
    external: true
  localhost.key:
    external: true

networks:
  appnet:
    external: true